# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    
    steps:
     
      - task: Docker@2
        displayName: 'Build Image'
        inputs:
          command: 'build'
          Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
          tags: '$(Build.BuildNumber)'
          arguments: '--build-arg BASEIMAGE=$(imageNameBase)'
    
      - task: ArtifactoryDocker@1
        inputs:
          command: 'push'
          artifactoryService: 'jfrog'
          targetRepo: 'vodapoc-docker'
          imageName: '$(imageName):$(Build.BuildNumber)'
          collectBuildInfo: true
          buildName: '$(Build.DefinitionName)'
          buildNumber: '$(Build.BuildNumber)'
          includeEnvVars: true

      - task: ArtifactoryPublishBuildInfo@1
        displayName: 'Publish Build Info'
        inputs:
          artifactoryService: 'jfrog'
          buildName: '$(Build.DefinitionName)'
          buildNumber: '$(Build.BuildNumber)'

